# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Columnar < Formula
  desc "A universal elastic tabstop code formatter"
  homepage "https://github.com/mudittt/columnar"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.1/columnar_darwin_amd64.tar.gz"
      sha256 "0eb1e3ac29be8ec7845d63f5626b5d67cfda25f8b8e097039aada5df9486e75c"

      define_method(:install) do
        bin.install "columnar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.1/columnar_darwin_arm64.tar.gz"
      sha256 "783fcce4da0ffd8706267cf18caa9866cfdfdd3a7ed9e084927c0635f856304d"

      define_method(:install) do
        bin.install "columnar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.1/columnar_linux_amd64.tar.gz"
      sha256 "a0c8fdac1c316ed4a900058fa6757c7d46b740558dbb4f032a70424e868dc309"
      define_method(:install) do
        bin.install "columnar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.1/columnar_linux_arm64.tar.gz"
      sha256 "1df71b3262ffd6f819458140858304fac01ec7e38554e04c7c3686654c5c185c"
      define_method(:install) do
        bin.install "columnar"
      end
    end
  end

  test do
    system "#{bin}/columnar", "--version"
  end
end
