# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Columnar < Formula
  desc "A universal elastic tabstop code formatter"
  homepage "https://github.com/mudittt/columnar"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.2/columnar_darwin_amd64.tar.gz"
      sha256 "32493a7e63272c58c7bcfd4f71648691ee67809a321111c1f5e63788ce9cebdc"

      define_method(:install) do
        bin.install "columnar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.2/columnar_darwin_arm64.tar.gz"
      sha256 "1d56c7192e3ad164b3a7764272a10ee5e943d7b90cfe3cf86eb1bb7889176da1"

      define_method(:install) do
        bin.install "columnar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.2/columnar_linux_amd64.tar.gz"
      sha256 "a9bafd674331134f0d9a75af4734efd97f1819c59a654d9b8016ce1ff57508fc"
      define_method(:install) do
        bin.install "columnar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mudittt/columnar/releases/download/v0.1.2/columnar_linux_arm64.tar.gz"
      sha256 "d80ee1dd3a6a53f0a037f20e8ce7e235afee14522ac44cb9142ec2458aa8cf03"
      define_method(:install) do
        bin.install "columnar"
      end
    end
  end

  test do
    system "#{bin}/columnar", "--version"
  end
end
